# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SocialDining' do

pod 'Google/CloudMessaging'
pod 'JSQMessagesViewController'
pod 'ObjectMapper', '~> 0.19'

use_frameworks!

end

target 'SocialDiningTests' do

end

